### PR TITLE
Make Ruler look more like Xcode by creating custom font. Make ruler font and ruler Inset scale with text font size.

### LINKED ISSUE #58: 🐞 Line number font is incorrect
The line number font does not align with Xcode.

image

Left: Xcode | Right: CodeEdit

The font needs to be sans-serif, narrower, with the color less prominent.

### LINKED ISSUE #157: ✨ Scale line numbers relative to font size
### Description

The line numbers in the ruler should scale relative to the editor font size as it increases or decreases. The line number font size is smaller than the editor font so it should scale proportionally.

### Screenshots

https://user-images.githubusercontent.com/806104/223864722-9276941a-22bc-4b62-b013-15ffaacc69d9.mp4

This is Xcode, we should be handling this similarly.

### PR DESCRIPTION
**Pull request by Eliulm**
### Description

This PR adds a customized SF Pro Font which aims to look like the Xcode Digits font. 
The ruler font and the ruler insets scale with the text font size. 

### Related Issues

* closes #58
* closes #157 

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code

### Screenshots

PointSize 13:
Xcode left, CodeEdit Right:
image

PointSize 20:
Xcode left, CodeEdit Right:
image

### CODE REVIEW

File: Sources/CodeEditTextView/Extensions/NSFont+RulerFont.swift [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+        let font = NSFont.systemFont(ofSize: fontSize, weight: fontWeight, width: fontWidth)
+
+        /// Set the open four
+        let alt4: [NSFontDescriptor.FeatureKey: Int] = [
+            .selectorIdentifier: kStylisticAltOneOnSelector,
+            .typeIdentifier: kStylisticAlternativesType
+        ]
+
+        /// Set alternate styling four 6 and 9
```
Comment (lukepistrol) [inline Sources/CodeEditTextView/Extensions/NSFont+RulerFont.swift:26]: I assume you meant `for` here 😉

**Review by austincondiff — DISMISSED** [review]
Looks good to me! Just fix that comment typo

**Review by lukepistrol — APPROVED** [review]
nice work 😊
