### PR TITLE
Line number color fixes

### LINKED ISSUE #166: 🐞 Line Number default color too prominent
### Description

The default line number color is too prominent compared to Xcode.

### Screenshots

Left: Xcode | Right: CodeEdit

Default Dark
image

Midnight
image

### Additional considerations

This seems to be more pronounced in dark mode. Check to make sure the fix is correct in both light and dark mode.

### Related issues

* #58

### PR DESCRIPTION
**Pull request by luah5**
### Description

this `PR` slightly changes the color of the line numbers, making it slightly darker

### Related Issues

* closes #166

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code
- [x] Change the line number color

### Screenshots

shot 2
shot 3

### CODE REVIEW

File: Sources/CodeEditTextView/Controller/STTextViewController.swift [hunk 1]
```diff
@@ -127,7 +127,10 @@ public class STTextViewController: NSViewController, STTextViewDelegate, ThemeAt
 
         rulerView = STLineNumberRulerView(textView: textView, scrollView: scrollView)
         rulerView.backgroundColor = useThemeBackground ? theme.background : .clear
-        rulerView.textColor = .systemGray
+        rulerView.textColor = .systemGray.blended(
+            withFraction: 0.5,
+            of: .darkGray
+        ) ?? .darkGray
```
Comment (lukepistrol) [inline Sources/CodeEditTextView/Controller/STTextViewController.swift:133]: I'd declare a private var in which computes this.

Somewhere at the top of the `class`:
```swift
private var rulerTextColor: NSColor {
    return .systemGray.blended(
        withFraction: 0.5
        of: .darkGray
    ) ?? .darkGray
}
```

This way it can be accessed anywhere in `STTextViewController`

Comment (lukepistrol) [reply Sources/CodeEditTextView/Controller/STTextViewController.swift:133]: Please also make sure that it looks good in both dark and light mode with both dark and light themes. Also append screenshots for each case with a comparison to the same setup in Xcode.

Comment (luah5) [reply Sources/CodeEditTextView/Controller/STTextViewController.swift:133]: I can verify it looks good in both light and dark mode, I'll show a screenshot

Comment (luah5) [reply Sources/CodeEditTextView/Controller/STTextViewController.swift]: i just added a screenshot

**Comment by austincondiff** [comment]
This approach is overlay verbose. All that is necessary is `.labelColor` for the current line number and `.secondaryLabelColor` for all of other line numbers.

**Review by austincondiff — CHANGES_REQUESTED** [review]
This approach is overlay verbose. All that is necessary is `.labelColor` for the current line number and `.secondaryLabelColor` for all of other line numbers.

File: Sources/CodeEditTextView/Controller/STTextViewController.swift [hunk 2]
```diff
@@ -127,7 +134,7 @@ public class STTextViewController: NSViewController, STTextViewDelegate, ThemeAt
 
         rulerView = STLineNumberRulerView(textView: textView, scrollView: scrollView)
         rulerView.backgroundColor = useThemeBackground ? theme.background : .clear
-        rulerView.textColor = .systemGray
+        rulerView.textColor = rulerTextColor
```
Comment (austincondiff) [inline Sources/CodeEditTextView/Controller/STTextViewController.swift:137]: Make the following changes...

```suggestion
        rulerView.textColor = .secondaryLabelColor
```

File: Sources/CodeEditTextView/Controller/STTextViewController.swift [hunk 3]
```diff
@@ -20,6 +20,13 @@ public class STTextViewController: NSViewController, STTextViewDelegate, ThemeAt
 
     internal var rulerView: STLineNumberRulerView!
 
+    private var rulerTextColor: NSColor {
+        return .systemGray.blended(
+            withFraction: 0.5,
+            of: .darkGray
+        ) ?? .darkGray
+    }
+
```
Comment (austincondiff) [inline Sources/CodeEditTextView/Controller/STTextViewController.swift:29]: Remove this variable...
```suggestion
```

**Review by austincondiff — CHANGES_REQUESTED** [review]

**Comment by luah5** [comment]
> This approach is overlay verbose. All that is necessary is `.labelColor` for the current line number and `.secondaryLabelColor` for all of other line numbers.

silly me, it was a very quick fix that didn't need that extra code

**Review by austincondiff — APPROVED** [review]

**Review by lukepistrol — APPROVED** [review]
